export const data = {
  dekan_fakultas_teknik: "Dony Susandi, S.T., M.T.",
  wakilDekan1: "Ade Bastian, S.T., M.Kom.",
  wakilDekan2: "Asep Rachmat, S.T., M.Kom.",
  kepala_program_studi: "Harun Sujadi, S.T., M.Kom.",
  kemahasiswaan: "Dadan Zaliluddin, S.T., M.Kom.",
  fasilitas:
    "laboratorium, ruang kelas yang dilengkapi dengan teknologi modern, perpustakaan, dan area diskusi (Yunus Diskusi dan Yunus Multimedia).",
  tentang_hmif: [
    "HMIF Universitas Majalengka berdiri pada tanggal 30 Maret 2011",
    "Terdapat 4 program studi di Fakultas Teknik: Informatika, Teknik Industri, Teknik Sipil, dan Teknik Mesin",
    "Struktur organisasi terdiri dari Dewan Pembina, Badan Pengurus Harian (BPH), dan Departemen",
    "Departemen meliputi LITBANG, Eksternal, Kominfo, dan DANUS",
    "Masa jabatan kepengurusan 1 periode sesuai SK Dekan",
  ],
  visi_misi: [
    "Visi: Menjadikan Himpunan Mahasiswa Informatika sebagai wadah yang inklusif dan inovatif untuk mengembangkan minat bakat, serta potensi mahasiswa",
    "Misi 1: Meningkatkan jiwa kepemimpinan dan kebersamaan",
    "Misi 2: Mengembangkan keterampilan soft skill dan hard skill",
    "Misi 3: Meningkatkan rasa kekeluargaan dan kerja sama dengan civitas akademik",
  ],
  bph: {
    ketua: "Aep Saepuloh",
    wakilKetua: "Desfi Silvia Aros",
    sekretaris1: "Mira Yunisa",
    sekretaris2: "Haura Zahra",
    Bendahara1: "Hegar Zalekania",
    Bendahara2: "Retno Sari Sirotujanah",
  },
  litbang: [
    "Abrar Wahid (Koordinator)",
    "Anis Agustin",
    "Zacky Hafsari",
    "Ayip Lutfy Firmansyah",
    "Wildan Zhilal Manafi",
    "Pandu Yassar Alfaros",
    "Puput Risna",
    "Rintan Nurhaliza",
    "Khoerul Anwar",
    "Kafi Agung Gunawan (Anggota Muda)",
    "Siti Solihah (Anggota Muda)",
    "Annisa Aprilia Lestari (Anggota Muda)",
  ],
  external: [
    "M Farhan Basyari (Koordinator)",
    "Hanabara Kuswara",
    "Siti Nurahma Dewi",
    "Nabhani Fatin",
    "Dwi Ferdiansyah",
    "Sunarjo",
    "M Fathu Rohman",
    "Fitriani Jayus Saputri (Anggota Muda)",
    "Yuda Tri Putra (Anggota Muda)",
  ],
  danus: [
    "Milhatun Nida (Koordinator)",
    "Nurhaeni Silvia",
    "Nur Alifaturohmah",
    "Dia Nuriah",
    "Ilham Fadilah",
    "Tri Maryani",
    "Shalma Primasari Dewi",
    "Anna Miftakhul Khoiriah (Anggota Muda)",
    "Joan Aryoadi (Anggota Muda)",
    "Aril Muhamad Nazih Arib Ardabil (Anggota Muda)",
  ],
  kominfo: [
    "Irki Septian Nurfadilah (Koordinator)",
    "Putri Nabila Kosasih",
    "Putri Maulidia",
    "M Farhan Fadila",
    "Salma Nurisa",
    "Riri Nurazizah",
    "Faizal Anugrah Pratama",
    "Maulana Nurafli",
    "Afifah Puteri (Anggota Muda)",
    "Faris Ilham Rabani (Anggota Muda)",
  ],
};
