export const data = {
  tentang_hmif: [
    "HMIF Universitas Majalengka berdiri pada tanggal 30 Maret 2011",
    "Terdapat 4 program studi di Fakultas Teknik: Informatika, Teknik Industri, Teknik Sipil, dan Teknik Mesin",
    "Struktur organisasi terdiri dari Dewan Pembina, Badan Pengurus Harian (BPH), dan Departemen",
    "Departemen meliputi LITBANG, Eksternal, Kominfo, dan DANUS",
    "Masa jabatan kepengurusan 1 periode sesuai SK Dekan",
  ],
  visi_misi: [
    "Visi: Menjadikan Himpunan Mahasiswa Informatika sebagai wadah yang inklusif dan inovatif untuk mengembangkan minat bakat, serta potensi mahasiswa",
    "Misi 1: Meningkatkan jiwa kepemimpinan dan kebersamaan",
    "Misi 2: Mengembangkan keterampilan soft skill dan hard skill",
    "Misi 3: Meningkatkan rasa kekeluargaan dan kerja sama dengan civitas akademik",
  ],
  bph: {
    ketua: "Aep Saepuloh",
    wakilKetua: "Desfi Silvia Aros",
    sekretaris1: "Mira Yunisa",
    sekretaris2: "Haura Zahra",
    Bendahara1: "Hegar Zalekania",
    Bendahara2: "Retno Sari Sirotujanah",
  },
  litbang: [
    "Abrar Wahid (Koordinator)",
    "Anis Agustin",
    "Zacky Hafsari",
    "Ayip Lutfy Firmansyah",
    "Wildan Zhilal Manafi",
    "Pandu Yassar Alfaros",
    "Puput Risna",
    "Rintan Nurhaliza",
    "Khoerul Anwar",
  ],
  external: [
    "M Farhan Basyari (Koordinator)",
    "Hanabara Kuswara",
    "Siti Nurahma Dewi",
    "Nabhani Fatin",
    "Dwi Ferdiansyah",
    "Sunarjo",
    "M Fathu Rohman",
  ],
  danus: [
    "Milhatun Nida (Koordinator)",
    "Nurhaeni Silvia",
    "Nur Alifaturohmah",
    "Dia Nuriah",
    "Ilham Fadilah",
    "Tri Maryani",
    "Shalma Primasari Dewi",
  ],
  kominfo: [
    "Irki Septian Nurfadilah (Koordinator)",
    "Putri Nabila Kosasih",
    "Putri Maulidia",
    "M Farhan Fadila",
    "Salma Nurisa",
    "Riri Nurazizah",
    "Faizal Anugrah Pratama",
    "Maulana Nurafli",
  ],
};
